name: Check on pull-request
on:
  pull_request:
  push:
    branches:
    - main

jobs:
  lint:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
    - name: Chckout pull request
      uses: actions/checkout@v2
    # - name: Copy bicep linter configuration for CI
    #   shell: bash
    #   run: |
    #     cp bicepconfig-ci.json bicepconfig.json
    # - name: Setup Bicep
    #   uses: anthony-c-martin/setup-bicep@v0.1
    #   with:
    #     version: v0.4.613
    # - name: Add problem matcher
    #   run: |
    #     echo "::add-matcher::.github/bicep_linter_error.json"
    #     echo "::add-matcher::.github/bicep_linter_warning.json"
    - name: Run Bicep build
      uses: azure/CLI@v1
      with:
        inlineScript: |
          for file in `ls **/*.bicep`; do
            mkdir -p ${RUNNER_TEMP}/`dirname $file`
            az bicep build --file $file --outdir ${RUNNER_TEMP}/`dirname $file`
            echo "$file checked"        
          done
      # with:
      #   inlineScript: |
      #     chmod +x "${GITHUB_WORKSPACE}/.github/linter.sh"
      #     "${GITHUB_WORKSPACE}/.github/linter.sh"
